// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/30/2026, 10:52:39 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Project Newdev/chatdevz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project Newdev/chatdevz/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project Newdev/chatdevz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project Newdev/chatdevz/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project Newdev/chatdevz/plugins/**/*.{js,ts,mjs}","C:/Project Newdev/chatdevz/composables/**/*.{js,ts,mjs}","C:/Project Newdev/chatdevz/utils/**/*.{js,ts,mjs}","C:/Project Newdev/chatdevz/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Project Newdev/chatdevz/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Project Newdev/chatdevz/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Project Newdev/chatdevz/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;